

criaCartao('Filmes de Ação', 'Qual é o filme onde Keanu Reeves interpreta um ex-assassino em busca de vingança?', 'John Wick')
criaCartao('Séries de Fantasia', 'Qual é a série que segue a jornada de Geralt de Rívia, um caçador de monstros?', 'The Witcher')
criaCartao('Filmes de Ficção Científica', 'Qual filme popular explora o conceito de sonhos dentro de sonhos?', 'A Origem (Inception)')
criaCartao('Séries de Drama', 'Qual série é ambientada em Albuquerque e acompanha a vida de um professor de química que se torna traficante?', 'Breaking Bad')
criaCartao('Filmes Clássicos', 'Em qual filme Humphrey Bogart diz a frase "We’ll always have Paris"?', 'Casablanca')
criaCartao('Séries de Mistério', 'Qual série começa com a misteriosa morte de Laura Palmer?', 'Twin Peaks')
criaCartao('Filmes de Terror', 'Qual filme popular apresenta um palhaço chamado Pennywise?', 'It: A Coisa')
criaCartao('Séries de Animação', 'Qual série animada segue as aventuras de Rick e Morty?', 'Rick and Morty')
criaCartao('Filmes de Super-Heróis', 'Qual filme da Marvel apresenta a batalha entre o Homem de Ferro e o Capitão América?', 'Capitão América: Guerra Civil')
criaCartao('Séries de Comédia', 'Qual série se passa no escritório fictício da Dunder Mifflin?', 'The Office')
criaCartao('Filmes de Romance', 'Qual filme de 1997 narra a tragédia do Titanic?', 'Titanic')
criaCartao('Séries de Ação', 'Qual série segue a história de um ex-presidiário chamado Michael Scofield?', 'Prison Break')
criaCartao('Filmes de Animação', 'Qual filme da Pixar apresenta uma amizade entre um cowboy e um astronauta?', 'Toy Story')
criaCartao('Séries de Suspense', 'Qual série é baseada em um jogo de sobrevivência com prêmios mortais?', 'Round 6 (Squid Game)')
criaCartao('Filmes de Drama', 'Qual filme conta a história de um mordomo que serve oito presidentes dos EUA?', 'O Mordomo da Casa Branca')
criaCartao('Séries de Ficção Científica', 'Qual série é ambientada no espaço e apresenta a nave USS Enterprise?', 'Star Trek')
criaCartao('Filmes Históricos', 'Qual filme retrata a vida de William Wallace na Escócia medieval?', 'Coração Valente')
criaCartao('Séries de Fantasia', 'Qual série tem dragões, reinos e uma luta pelo Trono de Ferro?', 'Game of Thrones')
criaCartao('Filmes de Suspense', 'Qual filme é conhecido pela frase "Eu vejo pessoas mortas"?', 'O Sexto Sentido')
criaCartao('Séries Policiais', 'Qual série segue a investigação de detetives em Baltimore?', 'The Wire')
criaCartao('Filmes de Aventura', 'Qual filme segue uma jornada para destruir o Um Anel?', 'O Senhor dos Anéis: A Sociedade do Anel')
criaCartao('Séries de Comédia', 'Qual série acompanha seis amigos vivendo em Nova York?', 'Friends')
criaCartao('Filmes Biográficos', 'Qual filme narra a vida de Freddie Mercury e a banda Queen?', 'Bohemian Rhapsody')
criaCartao('Séries de Terror', 'Qual série apresenta histórias de terror em temporadas independentes?', 'American Horror Story')
criaCartao('Filmes de Guerra', 'Qual filme de guerra de Christopher Nolan retrata a evacuação de soldados britânicos?', 'Dunkirk')
criaCartao('Séries de Mistério', 'Qual série da Netflix é ambientada em Hawkins e inclui o Mundo Invertido?', 'Stranger Things')
criaCartao('Filmes Musicais', 'Qual filme conta a história de um musical em Los Angeles entre dois sonhadores?', 'La La Land')
criaCartao('Séries de Drama Político', 'Qual série segue a ascensão política de Frank Underwood?', 'House of Cards')
criaCartao('Filmes de Terror', 'Qual filme popular apresenta a entidade sobrenatural chamada Valak?', 'Invocação do Mal 2')
criaCartao('Séries de Ação', 'Qual série narra a história de um advogado que se torna consultor de crimes?', 'Better Call Saul')
criaCartao('Filmes de Super-Heróis', 'Qual filme da DC apresenta a história do vilão Coringa?', 'Coringa (Joker)')
criaCartao('Séries de Animação', 'Qual série segue as vidas dos moradores de Springfield?', 'Os Simpsons')
criaCartao('Filmes Clássicos', 'Em qual filme Audrey Hepburn interpreta Holly Golightly?', 'Bonequinha de Luxo')
criaCartao('Séries de Ficção Científica', 'Qual série acompanha o Doutor em suas viagens no tempo?', 'Doctor Who')
criaCartao('Filmes de Mistério', 'Qual filme apresenta uma investigação sobre o desaparecimento de Amy Dunne?', 'Garota Exemplar (Gone Girl)')
criaCartao('Séries de Drama', 'Qual série explora a vida de Elizabeth II e a família real britânica?', 'The Crown')
criaCartao('Filmes de Aventura', 'Qual franquia segue as aventuras de um arqueólogo chamado Indiana Jones?', 'Indiana Jones')
criaCartao('Séries de Fantasia', 'Qual série apresenta as aventuras de um jovem aprendiz de mago chamado Merlin?', 'Merlin')
criaCartao('Filmes de Romance', 'Qual filme é baseado no livro de Nicholas Sparks e conta a história de Noah e Allie?', 'Diário de uma Paixão')
criaCartao('Séries de Suspense', 'Qual série explora a vida de Joe Goldberg, um stalker obsessivo?', 'You')
criaCartao('Filmes de Comédia', 'Qual filme apresenta um grupo de caçadores de fantasmas em Nova York?', 'Os Caça-Fantasmas (Ghostbusters)')
criaCartao('Séries de Mistério', 'Qual série segue um detetive que revive o mesmo dia para resolver um crime?', 'Russian Doll')
criaCartao('Filmes de Ficção Científica', 'Qual filme é ambientado em um mundo onde humanos vivem em uma simulação virtual?', 'Matrix')
criaCartao('Séries Policiais', 'Qual série segue os casos investigados pela Unidade de Vítimas Especiais de Nova York?', 'Law & Order: SVU')
criaCartao('Filmes de Suspense', 'Qual filme dirigido por Alfred Hitchcock apresenta um ataque de pássaros?', 'Os Pássaros')
criaCartao('Séries de Comédia', 'Qual série acompanha Ted Mosby contando a história de como conheceu a mãe de seus filhos?', 'How I Met Your Mother')

